baseURL = 'https://abgnpr.github.io/news-for-ga/'
languageCode = 'en-us'
title = 'News For General Awareness'
theme = 'hugo-PaperMod'

[params]
  author = "Abhigyan Prakash"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = false
  ShowToc = true
  ShowBreadCrumbs = true
  ShowShareButtons = false

[params.homeInfoParams]
  Title = "News For General Awareness"
  Content = "Weekly collection of current affairs and news insights from major newspapers"

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true

[[menu.main]]
  name = "Archives"
  url = "/archives/"
  weight = 1

[[menu.main]]
  name = "AI"
  url = "/ai/"
  weight = 2

[[menu.main]]
  name = "Energy"
  url = "/energy/"
  weight = 3

[[menu.main]]
  name = "Personal Finance"
  url = "/personal-finance/"
  weight = 4

[[menu.main]]
  name = "Curation Model"
  url = "/curation-model/"
  weight = 5

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 6

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 7

[outputs]
  home = ["HTML", "RSS", "JSON"]
